# Generated by Django 4.0 on 2022-10-09 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_permission'),
        ('tms', '0009_remove_reservation_reservation_date_and_more'),
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('service_needs', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_car', to='tms.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_user', to='login.user')),
            ],
        ),
    ]
