# Generated by Django 3.2.15 on 2022-10-04 13:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tms', '0009_remove_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=200)),
                ('arrival', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='drived date')),
                ('total_time', models.IntegerField(default=0)),
                ('total_range', models.IntegerField(default=0)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_id', to='tms.car')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
