# Generated by Django 4.0 on 2022-10-10 08:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('car_model', models.CharField(max_length=30, null=True)),
                ('can_ride', models.PositiveIntegerField(default=4)),
                ('propulsion_type', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('departure', models.CharField(default='', max_length=264)),
                ('destination', models.CharField(default='', max_length=264)),
                ('followers_num', models.PositiveIntegerField(default=0)),
                ('driving_by_self', models.BooleanField(default=False)),
                ('stopover', models.CharField(default='', max_length=264, null=True)),
                ('is_sharing', models.BooleanField(default=False)),
                ('reservation_start', models.DateTimeField(default=datetime.datetime.now, verbose_name='reservation start')),
                ('reservation_end', models.DateTimeField(default=datetime.datetime.now, verbose_name='reservation end')),
                ('status', models.IntegerField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=264, null=True)),
                ('safety_checklist', models.BooleanField(default=False)),
                ('operation_plan', models.CharField(default='', max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='created_at')),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booker', to='login.user')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='tms.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battalion_receiver', models.CharField(default='0', max_length=10)),
                ('permission', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=264, null=True)),
                ('status', models.CharField(blank=True, default='unread', max_length=264, null=True)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('type_of_notification', models.CharField(blank=True, max_length=264, null=True)),
                ('user_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to='login.user')),
            ],
        ),
    ]
