# Generated by Django 4.0 on 2022-09-25 07:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_is_superuser'),
        ('tms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, default='', max_length=264, null=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='reservation date')),
                ('is_approved', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, default='', max_length=264, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='created_at')),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booker', to='login.user')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='login.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='tms.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='tms.reservation'),
        ),
    ]
