# Generated by Django 4.0 on 2022-09-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0004_rename_name_car_car_model_car_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='battalion_receiver',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='permission',
            field=models.IntegerField(default=0),
        ),
    ]
