# Generated by Django 4.0 on 2022-10-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0006_car_can_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
    ]
