# Generated by Django 4.0 on 2022-10-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0007_alter_reservation_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='is_approved',
            new_name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='operation_plan',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='reservation',
            name='safety_checklist',
            field=models.BooleanField(default=False),
        ),
    ]
