# Generated by Django 4.0 on 2022-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0009_remove_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='operation_plan',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='stopover',
            field=models.CharField(default='', max_length=264, null=True),
        ),
    ]
