# Generated by Django 4.0 on 2022-10-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0010_alter_reservation_operation_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='driving_by_self',
            field=models.BooleanField(default=False),
        ),
    ]
