# Generated by Django 4.0 on 2022-10-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tms', '0011_reservation_driving_by_self'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reservation',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
