# Generated by Django 4.0 on 2022-10-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
